import streamlit as st

# =====================================================
# PAGE CONFIG
# =====================================================

st.set_page_config(
    page_title="About",
    page_icon="ℹ️",
    layout="wide"
)

# =====================================================
# HEADER
# =====================================================

st.title("ℹ️ About This Project")

st.caption(
    "Political & Election Analysis using Machine Learning"
)

st.divider()

# =====================================================
# PROJECT OVERVIEW
# =====================================================

st.header("📌 Project Overview")

st.write("""
The **Political & Election Analysis Dashboard** is a machine learning-based web
application developed to analyze historical election data and predict the
winning political party of an election constituency.

The application combines **interactive data visualization**, **historical
analysis**, and **machine learning** to provide meaningful insights into
election trends.
""")

st.divider()

# =====================================================
# OBJECTIVES
# =====================================================

st.header("🎯 Project Objectives")

st.markdown("""
- Predict the winning political party using Machine Learning.
- Analyze historical election data interactively.
- Compare different Machine Learning algorithms.
- Provide visual insights through interactive dashboards.
- Build a lightweight web application using Streamlit.
""")

st.divider()

# =====================================================
# DATASET
# =====================================================

st.header("📊 Dataset")

st.write("""
The project uses historical election data containing information such as:

- Election Year
- State
- Constituency
- Candidate
- Political Party
- Total Votes Polled
- Number of Electors
- Constituency Type

These features are processed and transformed into numerical representations
before training the machine learning models.
""")

st.divider()

# =====================================================
# TECHNOLOGIES
# =====================================================

st.header("💻 Technologies Used")

c1, c2 = st.columns(2)

with c1:

    st.markdown("""
### Programming

- Python
- Streamlit

### Data Processing

- Pandas
- NumPy
""")

with c2:

    st.markdown("""
### Machine Learning

- Scikit-Learn
- Joblib

### Visualization

- Plotly
""")

st.divider()

# =====================================================
# MACHINE LEARNING
# =====================================================

st.header("🤖 Machine Learning Pipeline")

st.code("""
Dataset
   ↓
Data Cleaning
   ↓
Feature Engineering
   ↓
Model Training
   ↓
Model Evaluation
   ↓
Model Selection
   ↓
Deployment
""")

st.success("""
The Decision Tree Classifier was selected as the deployment model because it
provides the highest accuracy (98.71%) while maintaining fast prediction speed
and low memory usage, making it ideal for real-time web deployment.
""")

st.divider()

# =====================================================
# KEY FEATURES
# =====================================================

st.header("✨ Key Features")

st.markdown("""
- 🔮 Election Winner Prediction
- 📊 Interactive Analysis Dashboard
- 📈 Historical Election Trends
- 🏆 Political Party Analysis
- 👤 Candidate Analysis
- 📄 Dataset Explorer
- 📥 Download Filtered Data
- 🤖 Machine Learning Model Comparison
""")

st.divider()

# =====================================================
# DEVELOPER
# =====================================================

st.header("👨‍💻 Developer")

st.info("""
**Project:** Political & Election Analysis using Machine Learning

**Developed By:** Abhinav T

**Purpose:** Internship Project (2026)

**Framework:** Streamlit

**Language:** Python
""")

st.divider()

# =====================================================
# DISCLAIMER
# =====================================================

st.header("📜 Disclaimer")

st.warning("""
This application has been developed solely for educational and internship
purposes.

The predictions generated by the machine learning model are based on historical
election data and should not be interpreted as actual future election results.
""")

st.divider()

# =====================================================
# FOOTER
# =====================================================

st.markdown(
"""
---
<center>

### 🗳 Political & Election Analysis Dashboard

Built using **Python • Streamlit • Plotly • Scikit-Learn**

© 2026 Internship Project

</center>
""",
unsafe_allow_html=True
)